spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
datasource:
  platform: h2
  url: jdbc:h2:mem:ddd-app
  username: sa
  password:
  driverClassName: org.h2.Driver


  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
server:
  error:
    whitelabel:
      enable: false

logging:
  level:
    org.springframework.orm: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
